# Generated by Django 2.1.5 on 2019-02-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pwd', models.IntegerField(max_length=20)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
